# Generated by Django 6.0.3 on 2026-03-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['race_date']},
        ),
        migrations.AddField(
            model_name='track',
            name='race_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
